# Generated by Django 5.0.3 on 2024-03-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TR1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('t10', models.DecimalField(decimal_places=25, max_digits=30)),
                ('t15', models.DecimalField(decimal_places=25, max_digits=30)),
                ('t20', models.DecimalField(decimal_places=25, max_digits=30)),
                ('t25', models.DecimalField(decimal_places=25, max_digits=30)),
                ('t30', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
        ),
    ]
